site_name: Priyankaâ€™s Technical Writing Portfolio
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

nav:
  - Overview: overview.md
  - My Documentation Workflow: workflow.md
  - How To Guide: how_to_guide.md
  - New Feature Alert: new_feature_alert.md
  - Thought Blog: thought_blog.md
  

plugins:
  - search
  - awesome-pages
